spring.application.name=Surya_Virtual_Diary
server.port=7070

# Database Configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1522/FREEPDB1
spring.datasource.username=diary_user
spring.datasource.password=diary_pass
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
